version: '3'
services:
  musicbrainz-picard:
    image: jlesage/musicbrainz-picard
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/musicbrainz-picard:/config:rw"
      - "/mnt/storage_box:/storage:rw"
    environment:
      - USER_ID: "1003"
      - GROUP_ID: "1004"
    # devices:
    #   - "/dev/sr0:/dev/sr0"
